version: '3.8'

services:
  database-postgres:
    image: emranb/database-postgres:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  server-node:
    image: emranb/server-node:latest
    ports:
      - "3000:3000"
    depends_on:
      - database-postgres
    environment:
      - DATABASE_HOST=database-postgres
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
      - DATABASE_NAME=mydb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  app-react:
    image: emranb/app-react:latest
    ports:
      - "1111:5173"
    depends_on:
      - server-node
    environment:
      - VITE_REACT_APP_API_HOST=localhost
      - VITE_REACT_APP_API_PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  postgres-data:
