name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Prune Docker system
        run: docker system prune -f

      - name: Build and Push Docker Images
        run: |
          # Build each service and push to Docker Hub
          docker build -t ${{ secrets.DOCKER_USERNAME }}/database-postgres ./src/database-postgres
          docker build -t ${{ secrets.DOCKER_USERNAME }}/server-node ./src/server-node
          docker build -t ${{ secrets.DOCKER_USERNAME }}/app-react ./src/app-react
          
          docker push ${{ secrets.DOCKER_USERNAME }}/database-postgres
          docker push ${{ secrets.DOCKER_USERNAME }}/server-node
          docker push ${{ secrets.DOCKER_USERNAME }}/app-react

      - name: Tear down Docker Compose
        run: docker-compose -f docker-compose.yml down
