name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Prune Docker system
        run: docker system prune -f

      - name: Build and Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml down
          docker-compose -f docker-compose.yml up --build -d

      - name: Wait for services to be ready
        run: sleep 15  # Adjust sleep time if necessary for services to initialize

      - name: Run tests (if any)
        run: |
          # Place your test commands here, for example:
          # curl http://localhost:1111 to check if the React app is running
          curl http://localhost:3000/health || echo "Backend service health check failed"
          curl http://localhost:1111 || echo "Frontend service check failed"

      - name: Tear down Docker Compose
        run: docker-compose -f docker-compose.yml down
